### ISSUE TITLE
get_node path detection

### ISSUE THREAD

**Issue by ksjogo** [johnfn/ts2gd#34]
In my new project (https://github.com/KronbergerSpiele/bloodfever) the get_node path detection seems to work well apart from two files:
scenes/game/Level.ts
scenes/loading/Loading.ts
They both have generated empty maps:
```
declare type NodePathToTypeLevel = {

}
```

**Comment by johnfn** [comment]
I'm having a little trouble loading your project because of this error:

![image](https://user-images.githubusercontent.com/167745/142961439-ca4e60bd-c3b3-4589-9003-47c9c99ab1db.png)

Mind including those files in the repo? Then I can try reproing this.

**Comment by ksjogo** [comment]
They seem to be in git, I will try with a clean checkout to see what happens.

**Comment by ksjogo** [comment]
Ahh, did you do:
`git submodule init`
﻿`git submodule update`
﻿?
﻿I have some files in a submodule.

**Comment by johnfn** [comment]
THANK you for the extensive project - I managed to fix a lot of bugs this way :-) 

Fixed this specific bug with https://github.com/johnfn/ts2gd/commit/4fc5a8502289dbf70a6d09f638378c904739af55

**Comment by ksjogo** [comment]
Yeah, I have been basically just reporting what I ran into when converting it to TS. :)

Is there some further trick to get these for Level and Loading? I updated to the latest commit, but they still don't seem to show up on my machine.
Looking through the generated types, I am also wondering if we should indeed add paths like these:
`  "/root/Level/Background/back": Sprite,`
That kind of assumes that a child always has the same parent on a type level.
OOP wise it would probably be cleaner if we only added paths of a scene childs.
But I didn't look into generation further yet.

**Comment by johnfn** [comment]
Ah you're right! I closed this too quickly. I will investigate those two files as well. 

The reason that I don't add root paths currently is that you can technically do something like `get_tree().change_scene("res://some/other/scene.tscn")` on ANY scene. That means that no root path is ever truly safe! 

Normally if I want root paths I'll just put a script on the topmost node in a scene and get them from there. Alternatively, you can make a scene an autoload, and then it'll be able to access root paths of the main scene, since that's one way I can guarantee it was instantiated only in the main scene.

I do think the lack of root access is annoying - the only problem is everything else I can see is worse! Unless we allow root paths only as long as they never do a scene change or something lol

**Comment by ksjogo** [comment]
It seems root paths get generated at the moment though like this
<img width="1157" alt="Screenshot 2021-11-25 at 18 12 56" src="https://user-images.githubusercontent.com/699858/143481319-84d63937-c06c-4987-bc96-019115f14f08.png">
Which I think comes from the fact that Level is having Pause in its tree.
I probably wouldn't put these there, as it indeed seems unsafe.

**Comment by johnfn** [comment]
Should be fixed with https://github.com/johnfn/ts2gd/commit/10faef89b7c3ed03d4754227c85fe86b5b76ef2d - feel free to give that a shot! I made some pretty big changes, so make sure everything is still working alright.
